language: node_js

node_js: stable

install:
  - yarn

script:
  - yarn run build

after_script:
  - cd ./dist
  - git init
  - git config user.name "tgly307"
  - git config user.email "tgly307@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

env:
 global:
   - GH_REF: github.com/tgly307/tgly307.github.io.git