language: node_js

node_js: stable

install:
  - npm install

script:
  - npm run build

after_script:
  - cd dist
  - git add --all .
  - git init
  - git config user.name "tgly307"
  - git config user.email "tgly307@163.com"
  - git add --all .
  - git commit -m "Automatically update from travis-ci"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

cache:
  npm: true
  directories:
    - node_modules

env:
 global:
   - GH_REF: github.com/tgly307/tgly307.github.io.git